on: workflow_dispatch
name: Manual Build Dashium
jobs:
  render:
    name: Build Dashium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: sudo apt update
      - run: npm install
      - run: npm run build
      - name: Chmod
        run: chmod +x ./release.sh
      - name: Update data and release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}